plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/robin/Desktop/github/pearl-wallet-showcase"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]